## 2.1 Generación y manejo de vectores y matrices. ##

#### Generación de vectores de forma directa ####

En el lenguaje M se va a trabajar habitualmente con los corchetes ([ ]) para la generación de vectores y matrices. Su uso implica un ensamblado de los elementos que aparecen en su interior para formar una construcción más compleja. Hacemos notar que no tiene el significado matemático similar a los paréntesis.

Para definir un vector no hace falta establecer de antemano su tamaño (de hecho, éste cambia de forma dinámica cuando es preciso). Simplemente, se disponen los valores de los elementos que lo van a componer entre corchetes, separados por espacios o una coma, en el caso de un vector fila, o por el carácter punto y coma (;) o pulsaciones intro, en el caso de un vector columna.

Al teclear

In [24]:
b=[1 2 3 4 5]

b =

   1   2   3   4   5



o bien

In [25]:
b=[1,2,3,4,5]

b =

   1   2   3   4   5



se genera el vector fila `b: 1 2 3 4 5`,
que aparecerá como tal en la ventana *Workspace*.

Mientras que:

In [26]:
c=[1;2;3]

c =

   1
   2
   3



o bien

In [27]:
c=[1
2
3]

c =

   1
   2
   3



genera el vector columna `c 1 2 3`

#### Generación rápida de vectores. Operador (:) ####

Se van a analizar a continuación otras formas de generación de vectores que no necesitan de la escritura explícita de todos sus elementos. Implícitamente se trabajará con el operador (:) que sirve para crear sucesiones numéricas, por ejemplo:

`1:4`, es equivalente a `1,2,3,4`

Define el vector cuyos primer y último elemento son los especificados por `vin` y `vfin`, estando los componentes intermedios separados por una unidad. Está permitido no utilizar los corchetes o sustituirlos por paréntesis.

Define el vector cuyos primer y último elemento son los especificados por `vin` y `vfin`, estando los componentes intermedios separados por `incr`. Está permitido no utilizar los corchetes o sustituirlos por paréntesis.

Genera un vector con `n` valores igualmente espaciados entre `x1` y `x2`.

#### Ejemplos: ####

In [28]:
v=[1:10]
v=1:10
v=(1:10)
v=[1:2:10]
v=linspace(1,10,7)

v =

    1    2    3    4    5    6    7    8    9   10

v =

    1    2    3    4    5    6    7    8    9   10

v =

    1    2    3    4    5    6    7    8    9   10

v =

   1   3   5   7   9

v =

    1.0000    2.5000    4.0000    5.5000    7.0000    8.5000   10.0000



## 2.2 Operaciones con matrices. Funciones específicas. ##

#### Operaciones con matrices mediante operadores ####

M puede operar con matrices por medio de *operadores* y por medio de *funciones*.

Sean `A` y `B` dos matrices y c un escalar. Los operadores matriciales del lenguaje M son los siguientes:

- Operadores suma (+) y resta (-)

Utilizado entre matrices (siempre con el mismo tamaño) obtiene la suma/resta matricial (elemento a elemento). Utilizado entre una matriz y un escalar, suma/resta el escalar a cada elemento de la matriz. No existen los operadores (.+) y (.-).

- Operador producto (*)

Utilizado entre matrices resuelve el producto matricial. Las dimensiones de las matrices deben ser congruentes. Utilizado entre una matriz y un escalar, multiplica el escalar por cada elemento de la matriz.

- Operador producto elemento a elemento (.*)

`A.*B` da como resultado una matriz cuyo elemento $ij$ es $A_{ij}*B_{i}$.

- Operador potenciación (^)

Para utilizarlo, al menos uno de los operandos debe ser un escalar y la matriz debe ser cuadrada.

`A^c` resuelve el producto matricial `A*A*A .............. *A`, c veces.

`c^A` se computa mediante autovalores y autofunciones.

- Operador potenciación elemento a elemento (.^)

A continuación aparecen todas las posibilidades de utilización:

   - `A.^B` da como resultado una matriz cuyo elemento $ij$ es $A_{ij}$\wedge$B_{ij}$.
   - `A.^c` da como resultado una matriz cuyo elemento $ij$ es $A_{ij}\wedge c$.
   - `c.^A` da como resultado una matriz cuyo elemento $ij$ es $c\wedge A_{ij}$.

- Operador división (/)(\)

La utilización entre una matriz y un escalar obtiene el cociente elemento a elemento. La utilización entre matrices se verá más adelante.

- Operador división elemento a elemento (./)(.\)

A continuación aparecen todas las posibilidades de utilización:

   - `A./B` da como resultado una matriz cuyo elemento `ij` es $A_{ij}/B_{ij}$.
   - `A.\B` da como resultado una matriz cuyo elemento `ij` es $B_{ij}/A_{ij}$.
 
- Operador traspuesta (')

`A'` da como resultado la matriz traspuesta de A.

In [29]:
a=[1 2 3];b=[4 5 6];c=3;
a+b
a.*b
a-b
a.^b
a+c
a*c
a.^c
c.^a

ans =

   5   7   9

ans =

    4   10   18

ans =

  -3  -3  -3

ans =

     1    32   729

ans =

   4   5   6

ans =

   3   6   9

ans =

    1    8   27

ans =

    3    9   27



- Operadores relacionales, lógicos y de igualdad

Son válidos los analizados en la sección 1.3. Aplicados entre matrices se emplean elemento a elemento, luego el tamaño de las matrices debe coincidir. El resultado es una matriz de tipo lógico.

In [30]:
A=1:9;
P=(A>2)&(A<6)

P =

  0  0  1  1  1  0  0  0  0



#### Operaciones con matrices mediante funciones ####

Además de los operadores analizados en la sección anterior, existen funciones M que permiten realizar otro tipo de operaciones con vectores:

- `dot(v,w)`producto escalar de los vectores `v` y `w`.
- `cross(v,w)`producto vectorial de los vectores `v` y `w` (máximo tres componentes de cada uno): $[v_2w_3-v_3w_2\quad v_3w_1-v_1w_3\quad v_1w_2-v_2w_1]$.
- `lenght(v)`calcula el número de componentes del vector v, o el máximo tamaño de las dimensiones si v es una matriz.
- `(m,n)=size(A)` devuelve el número de filas y de columnas de la matriz A. Si la matriz es cuadrada basta recoger el primer valor de retorno.
- `size(A,1)` devuelve el número de filas.
- `size(A,2)` devuelve el número de columnas.
- `max(v)` devuelve el valor de la mayor componente del vector `v`, o si `v` es una matriz genera un vector fila con el máximo de cada columna de la matriz.
- `min(v)` devuelve el valor de la menor componente del vector `v`, o si `v` es una matriz genera un vector fila con el mínimo de cada columna de la matriz.
- `norm(v)` obtiene el módulo del vector `v`
- `sum(v)` devuelve la suma de las componentes del vector `v`. Si `v` es matriz genera un vector fila, siendo cada elemento igual a la suma de la columna correspondiente de la matriz.
- `prod(v)` devuelve el producto de las componentes del vector `v`. Si `v` es matriz genera un vector fila, siendo cada elemento igual al producto de la columna correspondiente de la matriz.
- `sort(v)` ordena las componentes de v de menor a mayor. Si v es una matriz, ordena sus columnas de menor a mayor. Por ejemplo, para ordenar un vector v, bastaría con ejecutar la siguiente instrucción:

In [13]:
v=sort(v)

v =

    1.0000    2.5000    4.0000    5.5000    7.0000    8.5000   10.0000



A continuación se detallan algunas funciones que operan con matrices:
- `inv(A)` da como resultado la matriz inversa de $A$.
- `det(A)` da como resultado el determinante de $A$.
- `trace(A)` da como resultado la traza de $A$.
- `transpose(A)` Devuelve la matriz traspuesta de $A$.
- `A'` Devuelve la matriz traspuesta de $A$.

#### Funciones para definir matrices particulares ####

Existen en el lenguaje M varias funciones orientadas a definir con gran facilidad matrices de tipos particulares. Algunas de estas funciones son las siguientes:

- `eye(n)` forma la matriz *identidad* de tamaño $(n\times n)$
- `eye(m,n)` forma la matriz *identidad* de tamaño $(m\times n)$
- `zeros(m,n)` forma una matriz de *ceros* de tamaño $(m\times n)$
- `zeros(n)` forma una matriz de *ceros* de tamaño $(n\times n)$
- `ones(n)` forma una matriz de *unos* de tamaño $(n\times n)$
- `ones(m,n)` forma una matriz de *unos* de tamaño $(m\times n)$

In [14]:
eye(2)
zeros(2,3)
ones(4)

ans =

Diagonal Matrix

   1   0
   0   1

ans =

   0   0   0
   0   0   0

ans =

   1   1   1   1
   1   1   1   1
   1   1   1   1
   1   1   1   1



#### Números y matrices aleatorios ####

Para la generación de números y matrices pseudoaleatorios, $M$ dispone de las siguientes funciones:

- `rand` este comando genera números pseudoaleatorios distribuidos uniformemente entre 0 y 1. Cada llamada proporciona un nuevo número.
- `rand(n)` genera una matriz de números pseudoaleatorios entre 0 y 1, con distribución uniforme, de tamaño $(n\times n)$.
- `rand(m,n)` igual que en el caso anterior pero de tamaño $(m\times n)$.

In [15]:
rand
rand(3)

ans =  0.90489
ans =

   0.186232   0.801428   0.547975
   0.106503   0.918120   0.256544
   0.359537   0.503496   0.060026



#### Borrado de elementos de matrices y vectores ####

Se pueden crear nuevas matrices eliminando elementos de otras ya existentes. Para borrar elementos de una matriz o vector, se debe asignar a éstos el valor vacío entre corchetes [ ]. Ejemplo:

In [21]:
clc
%A(3,:)=[ ];

con esta orden se elimina la fila 3 de la matriz $A$.

#### Extracción de elementos de tablas mediante índices lógicos ####

Conocemos que para extraer elementos de una tabla, se deben indicar los índices correspondientes a los elementos; sin embargo, si como índices de una tabla disponemos un vector de tipo lógico, estamos indicando que se extraigan los elementos situados en las
posiciones de valor lógico 1. Ejemplo:

In [22]:
v=1:10
in=v>=5
v(in)
% se extraen los elementos de v que cumplen la condición, es elementos de v mayores o iguales a 5

v =

    1    2    3    4    5    6    7    8    9   10

in =

  0  0  0  0  1  1  1  1  1  1

ans =

    5    6    7    8    9   10



#### Reutilización del formato en escritura de matrices en pantalla ####

Cuando en lugar de un escalar se quiere escribir una matriz, se imprimirán los elementos en orden columnas, necesitando por cada elemento un formato. Sin embargo, en lenguaje M, ya conocemos que no es necesaria la disposición explícita de un formato por cada dato ya que cuando se termina de usar el formato especificado se reutiliza éste al completo hasta conseguir escribir el resto de datos. A continuación se escriben ejemplos relativos a esta propiedad:

In [23]:
A=[1 2;3 4]; B=[3.56 7.89];
fprintf('%d %d\n',A,B);
fprintf('El dato es: %f\n',B);

1 3
2 4
3.56 7.89
El dato es: 3.560000
El dato es: 7.890000


## 2.3 Resolución de sistemas de ecuaciones ##

En la mayor parte de problemas de ingeniería o ciencias aparecen sistemas de ecuaciones. Llegado este momento tenemos todas las herramientas necesarias para poder proceder a su resolución, siendo éste el objetivo de este tema.

Sea el sistema de ecuaciones que se expresa matricialmente de la forma $A\dot{x}=\dot{b}$, siendo $A$ la matriz de coeficientes, y $\dot{b}$ el vector de términos independientes. Este sistema puede resolverse en MATLAB y Octave utilizando simplemente el operador backslash o división izquierda (\) de la forma:

`x=A\b`

siendo $\dot{b}$ un vector columna. El operador \ examina los coeficientes de $A$ antes de intentar
resolver el sistema y actúa de la siguiente forma:

- Si $A$ es triangular (superior o inferior), entonces se utiliza sustitución hacia atrás o hacia delante.
- Si $A$ es simétrica y los elementos diagonales de $A$ son positivos, entonces se intenta la factorización de Cholesky. No siempre es posible realizarla porque aunque la matriz $A$ cumpla las condiciones dichas podría no ser definida positiva.
- Si las condiciones anteriores no se cumplen, se realiza una factorización $LU$.
- Si $A$ no es cuadrada, tiene tamaño $M\times N$ y se cumple que $M>N$ , el sistema se dice que es sobredeterminado. El sistema lineal resultante puede no tener solución. La solución que se adopta consiste en encontrar valores que minimicen el error dado por la siguiente expresión, lo que se denomina *Método de los Mínimos Cuadrados*:

$$e=\sum_{i=1}^{M}{\left(b_i-\sum_{j=1}^{N}a_{ij}x_{j}\right)}^{2} $$

Por ejemplo dado el sistema
\begin{align*}
2x+3y&=1,&\\
4x-y&=2, &\\
x-y&=3, &\\
x+y&=0, &
\end{align*}

el conjunto de instrucciones (programa) que finalizan con la resolución mediante el método de mínimos cuadrados es:

In [31]:
A=[2 3;4 -1;1 -1;1 1];
b=[1 2 3 0];
x=A\b'

x =

   0.61538
  -0.26923



- Si $A$ no es cuadrada, tiene tamaño $M\times N$ y se cumple que $N>M$, el sistema se denomina infradeterminado. Estos sistemas tienen infinitas soluciones y el operador \ se limita a seleccionar una sin enviar ningún mensaje de advertencia. Por ejemplo, si consideramos el sistema infradeterminado,
\begin{align*}
x+y+z&=-2.&\\
2x-3y&=-4,&
\end{align*}
el siguiente programa obtiene la solución indicada.

In [32]:
A=[1 1 1; 2 -3 0];
b=[-2,-4];
x=A\b'

x =

  -1.52632
   0.31579
  -0.78947



Sin embargo, existen otras muchas soluciones, por ejemplo: `x=1 ,y=2, z=-5`.

## 2.4 Estructuras de control de tipo condicional ##

Las sentencias de un programa son ejecutadas por el ordenador según su flujo natural, es decir, de arriba hacia abajo y de forma consecutiva a no ser que, de alguna manera, se altere este orden. Los comandos que realizan esta función se denominan comandos de control
de flujo y las sentencias a las que pertenecen sentencias de control de flujo.

Las sentencias condicionales permiten realizar ciertas instrucciones del programa sólo si se cumple la condición asociada a ellas.

