## 2.1 Generación y manejo de vectores y matrices. ##

### Generación de vectores de forma directa ###

En el lenguaje M se va a trabajar habitualmente con los corchetes ([ ]) para la generación de vectores y matrices. Su uso implica un ensamblado de los elementos que aparecen en su interior para formar una construcción más compleja. Hacemos notar que no tiene el significado matemático similar a los paréntesis.

Para definir un vector no hace falta establecer de antemano su tamaño (de hecho, éste cambia de forma dinámica cuando es preciso). Simplemente, se disponen los valores de los elementos que lo van a componer entre corchetes, separados por espacios o una coma, en el caso de un vector fila, o por el carácter punto y coma (;) o pulsaciones intro, en el caso de un vector columna.

Al teclear

In [1]:
b=[1 2 3 4 5]

b =

   1   2   3   4   5



o bien

In [2]:
b=[1,2,3,4,5]

b =

   1   2   3   4   5



se genera el vector fila `b: 1 2 3 4 5`,
que aparecerá como tal en la ventana *Workspace*.

Mientras que:

In [3]:
c=[1;2;3]

c =

   1
   2
   3



o bien

In [4]:
c=[1
2
3]

c =

   1
   2
   3



genera el vector columna `c = [1; 2; 3]`.

### Generación rápida de vectores. Operador (:) ###

Se van a analizar a continuación otras formas de generación de vectores que no necesitan de la escritura explícita de todos sus elementos. Implícitamente se trabajará con el operador (:) que sirve para crear sucesiones numéricas, por ejemplo:

`1:4`, es equivalente a `1,2,3,4`.

Define el vector cuyos primer y último elemento son los especificados por `vin` y `vfin`, estando los componentes intermedios separados por una unidad. Está permitido no utilizar los corchetes o sustituirlos por paréntesis.

Define el vector cuyos primer y último elemento son los especificados por `vin` y `vfin`, estando los componentes intermedios separados por `incr`. Está permitido no utilizar los corchetes o sustituirlos por paréntesis.

Genera un vector con `n` valores igualmente espaciados entre `x1` y `x2`.

### Ejemplos: ###

In [5]:
v=[1:10]
v=1:10
v=(1:10)
v=[1:2:10]
v=linspace(1,10,7) # linspace(inicio, cantidad de elementos, cota inferior)

v =

    1    2    3    4    5    6    7    8    9   10

v =

    1    2    3    4    5    6    7    8    9   10

v =

    1    2    3    4    5    6    7    8    9   10

v =

   1   3   5   7   9

v =

    1.0000    2.5000    4.0000    5.5000    7.0000    8.5000   10.0000



### Valor de las componentes de un vector ###

Como ya hemos visto, para crear un vector se utilizan los corchetes $[\;]\colon$

In [6]:
v = [3 5 7 9]

v =

   3   5   7   9



En cambio, para extraer o consultar el valor de las componentes de un vector ya existente, se utilizan los paréntesis $(\;)$

$$v(1)\rightarrow3$$

$$v(3)\rightarrow7$$

La palabra clave `end` se utiliza como índice para extraer el valor de la última componente del vector:

$$v(\text{end})\rightarrow9$$

In [7]:
v = [3 5 7 9]
v(1)
v(3)
v(end)

v =

   3   5   7   9

ans =  3
ans =  7
ans =  9


### Utilizar un vector de índices para extraer un subvector ###

Si lo que ponemos dentro de los paréntesis es a su vez un vector, sus valores se interpretan como los índices de las componentes que queremos extraer

$$P([1,\;3])\rightarrow\text{da como resultado un vector formado por la primera y tercera componentes del vector }P.$$

$$P([1\colon\;2\colon\;6])\rightarrow\text{da como resultado un vector formado por la primera(1), tercera(1+2=3) y quinta(3+2=5) componentes del vector }P.$$

In [8]:
P = [2, 3, 5, 7, 11, 13, 17, 19]
P([1,3]) # Índice 1 y 3.
P([1:2:6]) # Índice 1, 1+2=3, 3+2=5.

P =

    2    3    5    7   11   13   17   19

ans =

   2   5

ans =

    2    5   11



### Generación de matrices de forma directa ###

Para generar matrices de forma directa, se ponen los valores de sus elementos entre **corchetes** $[\;]$.

**Dentro de cada fila**, los elementos se separan por espacio o por coma.

**Para separar una fila de otra** se utiliza el punto y coma.

In [9]:
A=[1 2 3; 4 5 6; 7 8 9]

A =

   1   2   3
   4   5   6
   7   8   9



### Composición de matrices ###

Se pueden crear matrices componiendo a partir de otros vectores o matrices ya existentes.

In [10]:
A=[1 2; 3 4]
B=[5;6]
C=[A, B]
v1=[1 2 3]
v2=[4 5 6]
A=[v1; v2]
B=[v2; v1; v2]

A =

   1   2
   3   4

B =

   5
   6

C =

   1   2   5
   3   4   6

v1 =

   1   2   3

v2 =

   4   5   6

A =

   1   2   3
   4   5   6

B =

   4   5   6
   1   2   3
   4   5   6



### Consulta de elementos de una matriz ###

Para consultar el valor de un elemento de una matriz ya existente, se ponen su fila y columna entre paréntesis, separadas por coma.

$$A(2,3)\rightarrow\text{Devuelve el valor del elemento de la matriz }A\text{ situado en la fila 2, columna 3}.$$
$$A(3, \text{end})\rightarrow\text{Devuelve el elemento de la matriz }A\text{ situado en la última columna de la fila 3}.$$

In [11]:
A=magic(3) % Matriz mágina de orden 3.
A(2,3) % Elemento que está en la segunda fila y tercera columna.
A(3,end) % Elemento que está en la tercera fila y última columna.

A =

   8   1   6
   3   5   7
   4   9   2

ans =  7
ans =  2


### Extracción de submatrices ###

Si entre paréntesis, en lugar del valor de una fila y una columna, ponemos **dos vectores de índices**, el resultado será una **submatriz formada por la intersección de las filas y columnas** indicadas en los vectores de índices.

In [12]:
A=[1 2 3; 4 5 6; 7 8 9]
A
A([1 2], [2 3])

A =

   1   2   3
   4   5   6
   7   8   9

A =

   1   2   3
   4   5   6
   7   8   9

ans =

   2   3
   5   6



### Significado de los dos puntos utilizados como índice para extraer submatrices ###

Cuando al extraer elementos de una matriz, uno de los índices solicitados son **dos puntos** ':', se interpretan como toda la fila o toda la columna que corresponda.

$$A(:,3)\rightarrow\text{Devuelve la tercera columna de la matriz }A$$

$$A(1,:)\rightarrow\text{Devuelve la primera fila de la matriz }A$$

In [13]:
A=[1 2 3; 4 5 6; 7 8 9];
A(:,2)

ans =

   2
   5
   8



## 2.2 Operaciones con matrices. Funciones específicas. ##

### Operaciones con matrices mediante operadores ###

M puede operar con matrices por medio de *operadores* y por medio de *funciones*.

Sean `A` y `B` dos matrices y c un escalar. Los operadores matriciales del lenguaje M son los siguientes:

- Operadores suma (+) y resta (-)

Utilizado entre matrices (siempre con el mismo tamaño) obtiene la suma/resta matricial (elemento a elemento). Utilizado entre una matriz y un escalar, suma/resta el escalar a cada elemento de la matriz. No existen los operadores (.+) y (.-).

- Operador producto (*)

Utilizado entre matrices resuelve el producto matricial. Las dimensiones de las matrices deben ser congruentes. Utilizado entre una matriz y un escalar, multiplica el escalar por cada elemento de la matriz.

- Operador producto elemento a elemento (.*)

`A.*B` da como resultado una matriz cuyo elemento $ij$ es $A_{ij}*B_{i}$.

- Operador potenciación (^)

Para utilizarlo, al menos uno de los operandos debe ser un escalar y la matriz debe ser cuadrada.

`A^c` resuelve el producto matricial `A*A*A .............. *A`, c veces.

`c^A` se computa mediante autovalores y autofunciones.

- Operador potenciación elemento a elemento (.^)

A continuación aparecen todas las posibilidades de utilización:

   - `A.^B` da como resultado una matriz cuyo elemento $ij$ es $A_{ij}$\wedge$B_{ij}$.
   - `A.^c` da como resultado una matriz cuyo elemento $ij$ es $A_{ij}\wedge c$.
   - `c.^A` da como resultado una matriz cuyo elemento $ij$ es $c\wedge A_{ij}$.

- Operador división (/)(\)

La utilización entre una matriz y un escalar obtiene el cociente elemento a elemento. La utilización entre matrices se verá más adelante.

- Operador división elemento a elemento (./)(.\)

A continuación aparecen todas las posibilidades de utilización:

   - `A./B` da como resultado una matriz cuyo elemento `ij` es $A_{ij}/B_{ij}$.
   - `A.\B` da como resultado una matriz cuyo elemento `ij` es $B_{ij}/A_{ij}$.
 
- Operador traspuesta (')

`A'` da como resultado la matriz traspuesta de A.

In [14]:
a=[1 2 3];b=[4 5 6];c=3;
a+b
a.*b
a-b
a.^b
a+c
a*c
a.^c
c.^a

ans =

   5   7   9

ans =

    4   10   18

ans =

  -3  -3  -3

ans =

     1    32   729

ans =

   4   5   6

ans =

   3   6   9

ans =

    1    8   27

ans =

    3    9   27



- Operadores relacionales, lógicos y de igualdad

Son válidos los analizados en la sección 1.3. Aplicados entre matrices se emplean elemento a elemento, luego el tamaño de las matrices debe coincidir. El resultado es una matriz de tipo lógico.

### Suma y resta de matrices ###

Dos matrices de las mismas dimensiones se pueden sumar o restar.

La operación se realiza elemento a elemento.

In [15]:
A=[1 2; 3 4]
B=[1 0; 0 1]
A+B
A-B

A =

   1   2
   3   4

B =

   1   0
   0   1

ans =

   2   2
   3   5

ans =

   0   2
   3   3



### Producto de matrices ###

Dos matrices de dimensiones **congruentes** se pueden operar con el producto de matrices usual.

$$A_{(m,n)}\ast B_{(n,p)}\rightarrow C_{(m,p)}$$

In [16]:
A=[1;3;6;-2] % Matriz de orden 4x1.
B=[1 6 -2 0 -3] % Matriz de orden 1x5.
A*B % Matriz de orden 4x5.

A =

   1
   3
   6
  -2

B =

   1   6  -2   0  -3

ans =

    1    6   -2    0   -3
    3   18   -6    0   -9
    6   36  -12    0  -18
   -2  -12    4    0    6



### Matrices operadas con números ###

Si operamos un número con una matriz se hara elemento a elemento.

$$A+7\rightarrow\text{Suma siete a todos los elementos de }A.$$
$$A*2\rightarrow\text{Multiplica por dos a todos los elementos de }A.$$
$$A/1.5\rightarrow\text{Divide por 1.5 todos los elementos de }A.$$
$$A.*B$$


In [17]:
A=[1 1 1; 2 2 2; 3 3 3]
A+2
A*2
A/2

A =

   1   1   1
   2   2   2
   3   3   3

ans =

   3   3   3
   4   4   4
   5   5   5

ans =

   2   2   2
   4   4   4
   6   6   6

ans =

   0.50000   0.50000   0.50000
   1.00000   1.00000   1.00000
   1.50000   1.50000   1.50000



### Operadores elemento a elemento ###

Dos matrices de las mismas dimensiones la podemos operar elemento a elemento.

$$A.*B\rightarrow\text{Multiplica }A\text{ y }B\text{ elemento a elemento.}$$
$$A./B\rightarrow\text{Divide }A\text{ y }B\text{ elemento a elemento.}$$
$$A.^{\wedge}2\rightarrow\text{Eleva al cuadrado cada elemento de la matriz.}$$

In [18]:
A=[1 1; 2 2]
B=[3 3; 4 4]
A.*B
A.^2

A =

   1   1
   2   2

B =

   3   3
   4   4

ans =

   3   3
   8   8

ans =

   1   1
   4   4



### Obtener el tamaño de vectores y matrices ###

$$\text{lenght(v)}\rightarrow\text{ Devuelve el número de componentes del vector V.}$$
$$\text{[fil,col]=size(A)}\rightarrow\text{ Devuelve en fil el número de filas y en col el número de columnas de la matriz A}$$
$$\text{size(A,1)}\rightarrow\text{ Devuelve el número de filas de la matriz A.}$$
$$\text{size(A,2)}\rightarrow\text{ Devuelve el número de columnas de la matriz A.}$$

In [19]:
V=[1 2 3 4 5];
length(V)
A=[1 2 3; 4 5 6];
A
[fil, col]=size(A)
size(A,1)
size(A,2)

ans =  5
A =

   1   2   3
   4   5   6

fil =  2
col =  3
ans =  2
ans =  3


### Las funciones max(), min() ###

Sean $v$ un vector y $A$ una matriz:

$$\text{max}(v)\rightarrow\text{Devuelve el valor máximo (en módulo) de entre las componentes del vector }v.$$
$$\text{min}(v)\rightarrow\text{Devuelve el valor mínimo (en módulo) de entre las componentes del vector }v.$$
$$\text{max}(A)\rightarrow\text{Devuelve un vector fila con el máximo de cada columna de la matriz }A.$$
$$\text{min}(A)\rightarrow\text{Devuelve un vector fila con el mínimo de cada columna de la matriz }A.$$
$$\text{max}(\text{max}(A))\rightarrow\text{Devuelve el valor máximo de entre las componentes de la matriz }A.$$
$$\text{min}(\text{min}(A))\rightarrow\text{Devuelve el valor mínimo de entre las componentes de la matriz }A.$$

In [20]:
v=[i -2i]; # En el caso complejo imprime el valor de mayor módulo.
A=[2 3 5; 7 11 13];
max(v)
min(v)
max(A)
min(A)
max(max(A))
min(min(A))

ans = -0 - 2i
ans =  0 + 1i
ans =

    7   11   13

ans =

   2   3   5

ans =  13
ans =  2


### Las funciones sum(), prod() ###

Sean $v$ un vector y $A$ una matriz:

$$\text{sum}(v)\rightarrow\text{Devuelve la suma de las componentes del vector }v.$$
$$\text{prod}(v)\rightarrow\text{Devuelve el producto de las componentes del vector }v.$$
$$\text{sum}(A)\rightarrow\text{Devuelve un vector fila con la suma de cada columna de la matriz }A.$$
$$\text{prod}(A)\rightarrow\text{Devuelve un vector fila con el producto de las componentes de las columnas de la matriz }A.$$
$$\text{sum}(\text{sum}(A))\rightarrow\text{Devuelve la suma de las componentes de la matriz }A.$$
$$\text{prod}(\text{prod}(A))\rightarrow\text{Devuelve el producto de las componentes de la matriz }A.$$

In [21]:
v=[i -i 3 pi]
A=magic(4)
sum(v)
prod(v)
sum(A)
prod(A)
sum(sum(A))
prod(prod(A))

v =

 Columns 1 through 3:

   0.00000 + 1.00000i  -0.00000 - 1.00000i   3.00000 + 0.00000i

 Column 4:

   3.14159 + 0.00000i

A =

   16    2    3   13
    5   11   10    8
    9    7    6   12
    4   14   15    1

ans =  6.1416
ans =  9.4248
ans =

   34   34   34   34

ans =

   2880   2156   2700   1248

ans =  136
ans =    2.0923e+13


### La función sort() ###

Sean $v$ un vector y $A$ una matriz:

$$\text{sort}(v)\rightarrow\text{Devuelve un vector con las componentes de }v\text{ ordenadas de menor a mayor (en módulo)}.$$
$$\text{sort}(A)\rightarrow\text{Devuelve una matriz con los elementos de las columnas de }A\text{ ordenados de menor a mayor (en módulo)}.$$

In [22]:
v=[5 4 .2 i];
A=magic(5) # Visualice la matriz de orden 5.
sort(v)
sort(A)

A =

   17   24    1    8   15
   23    5    7   14   16
    4    6   13   20   22
   10   12   19   21    3
   11   18   25    2    9

ans =

 Columns 1 through 3:

   0.20000 + 0.00000i   0.00000 + 1.00000i   4.00000 + 0.00000i

 Column 4:

   5.00000 + 0.00000i

ans =

    4    5    1    2    3
   10    6    7    8    9
   11   12   13   14   15
   17   18   19   20   16
   23   24   25   21   22



### Producto escalar ###

Sean $v_1$ y $v_2$ dos vectores de las mismas dimensiones:

$$\text{dot}(v_1, v_2)\rightarrow\text{Devuelve el producto escalar de los dos vectores}.$$

### Producto vectorial ###

$$\text{cross}(v_1, v_2)\rightarrow\text{Devuelve el producto vectorial de los dos vectores }v_1\text{ y }v_2.$$

### Norma euclídeana ###

Sea $v$ un vector

$$\text{norm}(v)\rightarrow\text{Devuelve el módulo del vector }v.$$

In [23]:
v_1=[1 0 0]
v_2=[0 1 0]
dot(v_1, v_2)
cross(v_1, v_2)
norm(v_1)
norm(v_2)

v_1 =

   1   0   0

v_2 =

   0   1   0

ans = 0
ans =

   0   0   1

ans =  1
ans =  1


### Inversa, determinante, traza y traspuesta ###

Sea $A$ una matriz:

$$\text{inv}(A)\rightarrow\text{Devuelve la matriz inversa de la matriz }A.$$
$$\text{det}(A)\rightarrow\text{Devuelve la función multilineal alternada de la matriz }A.$$
$$\text{transpose}(A)\rightarrow\text{Devuelve la matriz traspuesta de }A.$$
$$A^{\prime}\rightarrow\text{Devuelve la matriz traspuesta conjugada de }A.$$

In [24]:
A=5*eye(5)-3*i*ones(5)
inv(A)
det(A)
transpose(A)
A'

A =

   5 - 3i  -0 - 3i  -0 - 3i  -0 - 3i  -0 - 3i
  -0 - 3i   5 - 3i  -0 - 3i  -0 - 3i  -0 - 3i
  -0 - 3i  -0 - 3i   5 - 3i  -0 - 3i  -0 - 3i
  -0 - 3i  -0 - 3i  -0 - 3i   5 - 3i  -0 - 3i
  -0 - 3i  -0 - 3i  -0 - 3i  -0 - 3i   5 - 3i

ans =

 Columns 1 through 3:

   0.164000 + 0.012000i  -0.036000 + 0.012000i  -0.036000 + 0.012000i
  -0.036000 + 0.012000i   0.164000 + 0.012000i  -0.036000 + 0.012000i
  -0.036000 + 0.012000i  -0.036000 + 0.012000i   0.164000 + 0.012000i
  -0.036000 + 0.012000i  -0.036000 + 0.012000i  -0.036000 + 0.012000i
  -0.036000 + 0.012000i  -0.036000 + 0.012000i  -0.036000 + 0.012000i

 Columns 4 and 5:

  -0.036000 + 0.012000i  -0.036000 + 0.012000i
  -0.036000 + 0.012000i  -0.036000 + 0.012000i
  -0.036000 + 0.012000i  -0.036000 + 0.012000i
   0.164000 + 0.012000i  -0.036000 + 0.012000i
  -0.036000 + 0.012000i   0.164000 + 0.012000i

ans =  3125.0 - 9375.0i
ans =

   5 - 3i  -0 - 3i  -0 - 3i  -0 - 3i  -0 - 3i
  -0 - 3i   5 - 3i  -0 - 3i  -0 - 3i  -0 - 3i
  -0 

#### Matrices particulares ###

$$\text{eye}(m)\rightarrow\text{Devuelve una matriz }\textbf{identidad}\text{ cuadrada de dimensión }m.$$
$$\text{eye}(m, n)\rightarrow\text{Devuelve una matriz }\textbf{identidad}\text{ con }m\text{ filas y }n\text{ columnas}.$$
$$\text{zeros}(m)\rightarrow\text{Devuelve una matriz }\textbf{de ceros}\text{ cuadrada de dimensión }m.$$
$$\text{zeros}(m, n)\rightarrow\text{Devuelve una matriz }\textbf{de ceros}\text{ con }m\text{ filas y }n\text{ columnas}.$$
$$\text{ones}(m)\rightarrow\text{Devuelve una matriz }\textbf{de unos}\text{ cuadrada de dimensión }m.$$
$$\text{ones}(m, n)\rightarrow\text{Devuelve una matriz }\textbf{de unos}\text{ con }m\text{ filas y }n\text{ columnas}.$$

In [25]:
eye(3)
zeros(3,6)
ones(4,8)

ans =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   1

ans =

   0   0   0   0   0   0
   0   0   0   0   0   0
   0   0   0   0   0   0

ans =

   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1



### Eliminar elementos de vectores y matrices ###

Podemos eliminar elementos de un vector o una matriz asignándooles el valor [] (corchetes vacíos). El resultado será el mismo vector o matriz con los elementos correspondientes eliminados. Veamos algunos ejemplos:

In [26]:
v=[1 2 3 4 5 6];
% Vamos a eliminar la tercera componente de v.
v(3)=[]
% Probemos ahora con una matriz
A=[1 2 3; 7 8 9]
% Vamos a eliminar la segunda columna.
A(:,2)=[]

v =

   1   2   4   5   6

A =

   1   2   3
   7   8   9

A =

   1   3
   7   9



### Operadores relacionales ###

Los operadores relacionales (<,>,<=,...) se pueden aplicar a vectores o matrices. Siempre operan elemento a elemento.

El resultado será un vector o matriz de las mismas dimensiones, con valores del tipo $\textbf{logical}$, verdadero (`true`,1) en los elementos que cumplan la condición y valores falso (`false`,0) en los elementos que no cumplan la condición.

In [27]:
v=[1 2 3 4 5 6];
V<4
A=[1 2 3; 4 5 6; 7 8 9]
A>=5

ans =

  1  1  1  0  0

A =

   1   2   3
   4   5   6
   7   8   9

ans =

  0  0  0
  0  1  1
  1  1  1



### Extracción de elementos con índices logical ###

Podemos crear un subvector de otro existente $v$, a partir de los elementos que cumplen una condición expresada con un operador relacional

$$v(v<5)\rightarrow\text{Subvector formado por las componentes del vector }v\text{ que son menores que }5.$$

In [28]:
v=1:10
v(v<5)

v =

    1    2    3    4    5    6    7    8    9   10

ans =

   1   2   3   4



### Generación de números (pseudoaleatorio) aleatorios ###

Para generar números aleatorios se utiliza la función `rand()`

$$\text{rand}()\rightarrow\text{Devuelve un número aleatorio entre cero y uno}.$$

* Nota 1: El número devuelto siempre será mayor que cero y menor que uno, esto es, pertenece al intervalo abierto (0,1).
* Nota 2: Los números aleatorios generados por ordenador nunca son aleaotorios puros, sino pseudoaleatorios.
* Para conocer más sobre esta clase de números y los algoritmos estándares para generar números pseudoaleatorios vea [aquí](https://www.youtube.com/watch?v=SxP30euw3-0).

In [29]:
rand()
rand()

ans =  0.37659
ans =  0.19738


### Matrices de números aleatorios ###

La función `rand()` permite generar matrices de números aleatorios con valores entre cero y uno.

$$\text{rand}(n)\rightarrow\text{Devuelve una matriz de números aleatorios entre cero y uno, con }n\text{ filas y }n\text{ columnas}.$$

$$\text{rand}(n, m)\rightarrow\text{Devuelve una matriz de números aleatorios entre cero y uno, con }n\text{ filas y }m\text{ columnas}.$$

In [30]:
rand(2,4)

ans =

   0.81833   0.17625   0.48695   0.52945
   0.42768   0.14795   0.62002   0.48634



### Números aleatorios en el intervalo (A, A+1) ###

Sea $A$ un valor real. Para generar números aleatorios en el intervalo $(A,A+1)$ utilizaremos la siguiente expresión:
$$A+\text{rand}()\rightarrow\text{Devuelve un número aleatorio en el intervalo }(A, A+1).$$

### Números aleatorios en el intervalo (0, A) ###

Sea $A$ un valor real. Para generar números aleatorios en el intervalo $(0,A)$ utilizaremos la siguiente expresión:

$$A*\text{rand}()\rightarrow\text{Devuelve un número aleatorio en el intervalo }(0, A).$$

In [31]:
A=5;
A+rand()
A*rand()

ans =  5.9643
ans =  4.9970


### Números aleatorios en el intervalo (A,B) ###

Sean $A$ y $B$ valores reales. Para generar números aleatorios en el intervalo $(A,B)$ utilizaremos la siguiente expresión:

$$A+(B-A)*\text{rand}()\rightarrow\text{Devuelve un número aleatorio en el intervalo} (A,B).$$

In [32]:
A=3;
B=5;
A+(B-A)*rand()
A+(B-A)*rand()

ans =  3.2237
ans =  3.1205


### Función round(): Redondear números decimales ###

La función `round()` devuelve el número entero más próximo al número decimal que recibe como argumento.

$$\text{round}(3,7)\rightarrow\text{Devuelve } 4.$$
$$\text{round}(3,2)\rightarrow\text{Devuelve } 3.$$

Nota: Cuando el valor es justo .5, redondea al entero siguiente, por ejemplo, `round(1.5)` devuelve 2.

In [33]:
200/7
round(200/7)
round([pi,e])
round([pi*i,i*e])
% Para más información vea
help round

ans =  28.571
ans =  29
ans =

   3   3

ans =

   0 + 3i   0 + 3i

'round' is a built-in function from the file libinterp/corefcn/mappers.cc

 -- round (X)
     Return the integer nearest to X.

     If X is complex, return 'round (real (X)) + round (imag (X)) * I'.
     If there are two nearest integers, return the one further away from
     zero.

          round ([-2.7, 2.7])
               => -3    3

     See also: ceil, floor, fix, roundb.

Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at http://www.octave.org and via the help@octave.org
mailing list.


### Números aleatorios enteros ###

Utilizando la función `round()` combinada con la función `rand()` podemos generar números aleatorios enteros.

Para generar un número entero aleatorio en intervalo $\underline{cerrado}$ $[A,B]$ utilizaremos la siguiente expresión:

$$\text{round}(A+(B-A)*\text{round}())\rightarrow\text{Devuelve un número entero aleatorio en el intervalo cerrado }[A,B].$$

In [34]:
% Simulación de tiradas de un dado de seis caras
A=1;
B=6;
round(A+(B-A)*rand())
round(A+(B-A)*rand())

ans =  4
ans =  1


In [35]:
A=1:9;
% Vector fila A que tiene elementos del 1 al 9.
P=(A>2)&(A<6)
% El vector P imprime 1 para las entradas donde se cumpla la proposición.

P =

  0  0  1  1  1  0  0  0  0



### Operaciones con matrices mediante funciones ###

Además de los operadores analizados en la sección anterior, existen funciones M que permiten realizar otro tipo de operaciones con vectores:

- `dot(v,w)`producto escalar de los vectores `v` y `w`.
- `cross(v,w)`producto vectorial de los vectores `v` y `w` (máximo tres componentes de cada uno): $[v_2w_3-v_3w_2\quad v_3w_1-v_1w_3\quad v_1w_2-v_2w_1]$.
- `lenght(v)`calcula el número de componentes del vector v, o el máximo tamaño de las dimensiones si v es una matriz.
- `(m,n)=size(A)` devuelve el número de filas y de columnas de la matriz A. Si la matriz es cuadrada basta recoger el primer valor de retorno.
- `size(A,1)` devuelve el número de filas.
- `size(A,2)` devuelve el número de columnas.
- `max(v)` devuelve el valor de la mayor componente del vector `v`, o si `v` es una matriz genera un vector fila con el máximo de cada columna de la matriz.
- `min(v)` devuelve el valor de la menor componente del vector `v`, o si `v` es una matriz genera un vector fila con el mínimo de cada columna de la matriz.
- `norm(v)` obtiene el módulo del vector `v`
- `sum(v)` devuelve la suma de las componentes del vector `v`. Si `v` es matriz genera un vector fila, siendo cada elemento igual a la suma de la columna correspondiente de la matriz.
- `prod(v)` devuelve el producto de las componentes del vector `v`. Si `v` es matriz genera un vector fila, siendo cada elemento igual al producto de la columna correspondiente de la matriz.
- `sort(v)` ordena las componentes de v de menor a mayor. Si v es una matriz, ordena sus columnas de menor a mayor. Por ejemplo, para ordenar un vector v, bastaría con ejecutar la siguiente instrucción:

In [36]:
v=sort(v)

v =

    1    2    3    4    5    6    7    8    9   10



A continuación se detallan algunas funciones que operan con matrices:
- `inv(A)` da como resultado la matriz inversa de $A$.
- `det(A)` da como resultado el determinante de $A$.
- `trace(A)` da como resultado la traza de $A$.
- `transpose(A)` Devuelve la matriz traspuesta de $A$.
- `A'` Devuelve la matriz traspuesta de $A$.

### Funciones para definir matrices particulares ###

Existen en el lenguaje M varias funciones orientadas a definir con gran facilidad matrices de tipos particulares. Algunas de estas funciones son las siguientes:

- `eye(n)` forma la matriz *identidad* de tamaño $(n\times n)$
- `eye(m,n)` forma la matriz *identidad* de tamaño $(m\times n)$
- `zeros(m,n)` forma una matriz de *ceros* de tamaño $(m\times n)$
- `zeros(n)` forma una matriz de *ceros* de tamaño $(n\times n)$
- `ones(n)` forma una matriz de *unos* de tamaño $(n\times n)$
- `ones(m,n)` forma una matriz de *unos* de tamaño $(m\times n)$

In [37]:
eye(2)
zeros(2,3)
ones(4)

ans =

Diagonal Matrix

   1   0
   0   1

ans =

   0   0   0
   0   0   0

ans =

   1   1   1   1
   1   1   1   1
   1   1   1   1
   1   1   1   1



### Números y matrices aleatorios ###

Para la generación de números y matrices pseudoaleatorios, $M$ dispone de las siguientes funciones:

- `rand` este comando genera números pseudoaleatorios distribuidos uniformemente entre 0 y 1. Cada llamada proporciona un nuevo número.
- `rand(n)` genera una matriz de números pseudoaleatorios entre 0 y 1, con distribución uniforme, de tamaño $(n\times n)$.
- `rand(m,n)` igual que en el caso anterior pero de tamaño $(m\times n)$.

In [38]:
rand
rand(3)

ans =  0.44426
ans =

   0.190950   0.330327   0.015725
   0.483988   0.850487   0.086358
   0.205391   0.085847   0.914069



### Borrado de elementos de matrices y vectores ###

Se pueden crear nuevas matrices eliminando elementos de otras ya existentes. Para borrar elementos de una matriz o vector, se debe asignar a éstos el valor vacío entre corchetes [ ]. Ejemplo:

In [39]:
clc
%A(3,:)=[ ];

con esta orden se elimina la fila 3 de la matriz $A$.

### Extracción de elementos de tablas mediante índices lógicos ###

Conocemos que para extraer elementos de una tabla, se deben indicar los índices correspondientes a los elementos; sin embargo, si como índices de una tabla disponemos un vector de tipo lógico, estamos indicando que se extraigan los elementos situados en las
posiciones de valor lógico 1. Ejemplo:

In [40]:
v=1:10
in=v>=5
v(in) % se extraen los elementos de v que cumplen la condición, es elementos de v mayores o iguales a 5

v =

    1    2    3    4    5    6    7    8    9   10

in =

  0  0  0  0  1  1  1  1  1  1

ans =

    5    6    7    8    9   10



### Reutilización del formato en escritura de matrices en pantalla ###

Cuando en lugar de un escalar se quiere escribir una matriz, se imprimirán los elementos en orden columnas, necesitando por cada elemento un formato. Sin embargo, en lenguaje M, ya conocemos que no es necesaria la disposición explícita de un formato por cada dato ya que cuando se termina de usar el formato especificado se reutiliza éste al completo hasta conseguir escribir el resto de datos. A continuación se escriben ejemplos relativos a esta propiedad:

In [41]:
A=[1 2;3 4]; B=[3.56 7.89];
fprintf('%d %d\n',A,B);
fprintf('El dato es: %f\n',B);

1 3
2 4
3.56 7.89
El dato es: 3.560000
El dato es: 7.890000


## 2.3 Resolución de sistemas de ecuaciones ##

En la mayor parte de problemas de ingeniería o ciencias aparecen sistemas de ecuaciones. Llegado este momento tenemos todas las herramientas necesarias para poder proceder a su resolución, siendo éste el objetivo de este tema.

Sea el sistema de ecuaciones que se expresa matricialmente de la forma $A\dot{x}=\dot{b}$, siendo $A$ la matriz de coeficientes, y $\dot{b}$ el vector de términos independientes. Este sistema puede resolverse en MATLAB y Octave utilizando simplemente el operador backslash o división izquierda (\) de la forma:

`x=A\b`

siendo $\dot{b}$ un vector columna. El operador \ examina los coeficientes de $A$ antes de intentar
resolver el sistema y actúa de la siguiente forma:

- Si $A$ es triangular (superior o inferior), entonces se utiliza sustitución hacia atrás o hacia delante.
- Si $A$ es simétrica y los elementos diagonales de $A$ son positivos, entonces se intenta la factorización de Cholesky. No siempre es posible realizarla porque aunque la matriz $A$ cumpla las condiciones dichas podría no ser definida positiva.
- Si las condiciones anteriores no se cumplen, se realiza una factorización $LU$.
- Si $A$ no es cuadrada, tiene tamaño $M\times N$ y se cumple que $M>N$ , el sistema se dice que es sobredeterminado. El sistema lineal resultante puede no tener solución. La solución que se adopta consiste en encontrar valores que minimicen el error dado por la siguiente expresión, lo que se denomina *Método de los Mínimos Cuadrados*:

$$e=\sum_{i=1}^{M}{\left(b_i-\sum_{j=1}^{N}a_{ij}x_{j}\right)}^{2} $$

Por ejemplo dado el sistema
\begin{cases}
2x+3y=1\\
4x-y=2 \\
x-y=3\\
x+y=0 
\end{cases}

el conjunto de instrucciones (programa) que finalizan con la resolución mediante el método de mínimos cuadrados es:

In [42]:
A=[2 3;4 -1;1 -1;1 1];
b=[1 2 3 0];
x=A\b'

x =

   0.61538
  -0.26923



- Si $A$ no es cuadrada, tiene tamaño $M\times N$ y se cumple que $N>M$, el sistema se denomina infradeterminado. Estos sistemas tienen infinitas soluciones y el operador \ se limita a seleccionar una sin enviar ningún mensaje de advertencia. Por ejemplo, si consideramos el sistema infradeterminado,
\begin{align*}
x+y+z&=-2.&\\
2x-3y&=-4,&
\end{align*}
el siguiente programa obtiene la solución indicada.

In [43]:
A=[1 1 1; 2 -3 0];
b=[-2,-4];
x=A\b'

x =

  -1.52632
   0.31579
  -0.78947



Sin embargo, existen otras muchas soluciones, por ejemplo: `x=1 ,y=2, z=-5`.

### Representación algebraica de un sistema de ecuaciones ###

\begin{cases}
x-3y+2z=-3\\
5x+6y-z=13\\
4x-y+3z=8\\
\end{cases}

### Representación matricial de un sistema de ecuaciones ###

\begin{gather}
 \begin{pmatrix}
 1 & -3 & 2 \\
 5 & 6 & -1 \\
 4 & -1 & 3
 \end{pmatrix}
  \begin{pmatrix}
   x \\
   y \\
   z
  \end{pmatrix}
 =
  \begin{pmatrix}
  -3 \\ 13 \\ 8
  \end{pmatrix}
\end{gather}

$$Ax=B$$

### Solución cuando la matriz de coeficientes no es singular ###

\begin{align*}
A x & = B \\
A^{-1} A x & = A^{-1} B \\
I X & = A^{-1} B
\end{align*}

$$\boxed{x=A^{-1}B}$$

In [44]:
A=[1 -3 2; 5 6 -1; 4 -1 3]
B=[-3; 13; 8]
inv(A)
x=inv(A)*B

A =

   1  -3   2
   5   6  -1
   4  -1   3

B =

   -3
   13
    8

ans =

   1.06250   0.43750  -0.56250
  -1.18750  -0.31250   0.68750
  -1.81250  -0.68750   1.31250

x =

  -2.0000
   5.0000
   7.0000



### Solución optimizando el procedimiento ###

$$\boxed{X=A\backslash B}$$

In [45]:
A=[1 -3 2; 5 6 -1; 4 -1 3]
B=[-3;13;8]
x=A\B

A =

   1  -3   2
   5   6  -1
   4  -1   3

B =

   -3
   13
    8

x =

  -2.0000
   5.0000
   7.0000



## 2.4 Estructuras de control de tipo condicional ##

Las sentencias de un programa son ejecutadas por el ordenador según su flujo natural, es decir, de arriba hacia abajo y de forma consecutiva a no ser que, de alguna manera, se altere este orden. Los comandos que realizan esta función se denominan comandos de control
de flujo y las sentencias a las que pertenecen sentencias de control de flujo.

Las sentencias condicionales permiten realizar ciertas instrucciones del programa sólo si se cumple la condición asociada a ellas.

- Sentencia `if` simple
La forma básica de una sentencia condicional `if` es la siguiente:

        if  expresión_lógica
    
            sentencias
    
        end
o bien

`if expresión_lógica , sentencias , end`

Las sentencias se ejecutan sólo si la expresión lógica se evalúa como cierta, en el caso de que la expresión sea evaluada como falsa, el programa continúa por la instrucción siguiente a end sin realizar las sentencias asociadas al condicional.

- Bloque `if` unicondicional 

Se trata de otro tipo de sentencia más compleja pero en la que sigue apareciendo una única expresión lógica. La sintaxis se indica a continuación.

    if  expresión_lógica
       
        bloque 1 sentencias
    else
    
        bloque 2 sentencias
    end

Si la expresión lógica se evalúa como cierta se ejecuta el bloque 1 de sentencias, si se evalúa como falsa se ejecuta el bloque 2. Nunca se ejecutan los dos bloques de sentencias a la vez, ni ninguno de los dos. Se utiliza para elegir uno de dos 'caminos' en el programa.

- Bloque `if` multicondicional

A continuación mostramos la sintaxis de otra expresión condicional en la que se pueden evaluar dos o más condiciones.

    if  expresión_lógica_1
        bloque 1 sentencias
    elseif  expresión_lógica_2
         bloque 2 sentencias
        ............
    elseif  expresión_lógica_n
         bloque n sentencias
    else
         bloque n+1 sentencias
    end
    
Su funcionamiento es simple, la primera expresión lógica que se evalúe como cierta provoca la ejecución de sus sentencias asociadas y el posterior abandono de la estructura completa. Se utiliza para elegir uno de varios 'caminos' en el programa.

La última rama (`else`) es opcional. Si se escribe, solo se ejecuta el bloque perteneciente a ella si todas las expresiones lógicas anteriores han resultado falsas.

Veamos unos ejemplos de estas estructuras.

En el siguiente programa se estudia si un número n es múltiplo de 2 y/o de 3.

In [47]:
n = input('Digite un número entero:')

if  rem(n,2)==0
    disp('Es múltpiplo de 2.')
end

if  rem(n,3)==0
    disp('Es múltiplo de 3.')
end

Digite un número entero:5
n =  5


Obsérvese que las dos condiciones a estudiar son independientes: el cumplimiento o no de la primera no induce a que la segunda se cumpla o no. Cuando ocurra esto se deben estudiar los casos de forma independiente usando `if` simples.

En el siguiente programa, se elige entre una de dos alternativas posibles (par o impar). Un número es par o es impar, no puede ser las dos opciones a la vez ni ninguna de ellas. Cuando ocurran estos casos se debe utilizar la estructura `if`/`else`.

In [48]:
n=input ('Introduce un entero positivo');
if  rem(n,2)== 0
        disp('n es par')
else
        disp('n es impar')
end

Introduce un entero positivo5
n es impar


A continuación se incorpora al programa anterior una tercera opción, número negativo, que aumenta a tres las posibilidades de elección. Cuando tengamos más de dos posibilidades excluyentes se debe usar la estructura `if` / `elseif` / `else`.

A continuación se incorpora al programa anterior una tercera opción, número negativo, que
aumenta a tres las posibilidades de elección. Cuando tengamos más de dos posibilidades
excluyentes se debe usar la estructura `if` / `elseif` / `else`.

In [49]:
rem(25,7) % Porque 25 = 7 * 3 + 4.
rem(7,2) % Porque 7 = 2 * 3 + 1.
rem(12,2)==0

ans =  4
ans =  1
ans = 1


In [51]:
n = input('Introduce un entero');
if  n<0
    disp('n es negativo')
elseif  rem(n,2)== 0
        disp('n es par')
else
        disp('n es impar')
end

Introduce un entero5
n es impar
