# Tercera clase #

## Ejercicio s0100.m ###
**Instrucciones:**
1. Pida ingresar un valor, por ejemplo $n=\ln(2017.2083)$.
2. Imprima el valor de $n$ con cuatro decimales. Use formato short.
3. Imprima el valor de $n$ con quince decimales. Use formato long.
4. Imprima el valor de $n$ en hexadecimal. Use formato hex.
5. Imprima el valor de $n$ como fracción. Use formato rat.

In [2]:
% Aplicación de formato numérico.
clc; clear;
n = input('Ingrese un valor: '); %Por ejemplo log(2017.2083).
format; % format short;
disp('format short'); disp(n);
format long; disp('format long'); disp(n);
format +; disp('format +'); disp(n);
format bank; disp('format hex'); disp(n);
format rat; disp('format rat'); disp(n);

Ingrese un valor:1
format short
 1
format long
 1
format +
+
format hex
 1.00
format rat
1


## Ejercicio s0101.m ###
**Instrucciones:**
1. Pida ingresar un valor, por ejemplo $n=\ln(2017.2083)$.
2. Imprima el valor de $n$ con cuatro.

In [5]:
% Aplicación de formato numérico
clc; clear;
n = input('Ingrese un valor: ');
% Pruebe para pi, exp(1)
format compact;
format short; disp('format short'); disp(n);
format long; disp('format long'); disp(n);
format short e; disp('format short e'); disp(n);
format long e; disp('format long e'); disp(n);
format short g; disp('format short g'); disp(n);
format long g; disp('format long g'); disp(n);
format short eng; disp('format short eng'); disp(n);
format long eng; disp('format longng eng'); disp(n);
format +; disp('format +'); disp(n);
format bank; disp('format bank'); disp(n);
format hex; disp('format hex'); disp(n);
format rat; disp('format rat'); disp(n);

Ingrese un valor:20
format short
 20
format long
 20
format short e
   2.0000e+01
format long e
   2.00000000000000e+01
format short g
        20
format long g
                  20
format short eng
   20.0000e+000
format longng eng
   20.00000000000000e+000
format +
+
format bank
 20.00
format hex
4034000000000000
format rat
20


## Ejercicio s0102.m ###
**Instrucciones:**
1. Pida.

In [ ]:
3^2 %^alt+ 94
-3^2
16^(1/2)
(-3)^3
-27^(1/3)
3^2-5-6/3*2
3^2-5-6/(3*2)
4*3^2+1
(4*3)^2+1
1/2*21.3*12.6
21.3*12.6/2
base = 21.3
altura = 12.6
area = 1/2 * base * altura
namelengthmax
iskeyword
a = 2, b = 3; c = 5
d = a * b + c;
d
x = 25, ...
y = x/5
a = 2; b =3;
area = a*b/2
a = 1+2+3+4+5+6+7+8+9+10
b = 1-2+3-4+5-6+7-8+9-10
exp(1)
log(3)
log10(3)
log2(3)
sqrt(64)
sin(pi/3)
sqrt(16)
16^(1/2)
e = exp(1)
log10(e)
log2(e)
pi/4
atan(1)
log(e)

`abs(x)` Valor absoluto de `x`.

`fix(x)` Redondea `x` hacia cero.

`floor(x)` Redondea `x` hacia menos infinito.

`ceil(x)` Redondea `x` hacia más

`round(x)` Redondea `x`.

`rem(m,n)` Operación módulo entre `m` y `n`.

`rand` Número aleatorio entre 0 y 1.

In [6]:
x = -28;
y = abs(x)
a = 20/3
rem(20,3)
rand
fix(-5.7), fix(5.7)
floor(-5.7), floor(5.7)
ceil(-5.7), ceil(5.7)
round(-5.7), round(5.7)
[1 3 5 -7 0.33 pi exp(1)]
[1, 3, 5, -7, 0.33, pi, exp(1)]
v=[1 3 5 -7 0.33 pi exp(1)]
[10:2:20]
[15:1:19]
[1:0.5:2]
[20:-0.3:18]
[11:15]
[-3:3]
[17:20]
x=[-3 -2 -1 0 1 2 3 4 5 6 7 8]
x=[-3:1:8]
x=[-3:8]
x=(-3:8)
x=-3:8
x=-3:8.7
x=linspace(-3,8,12)
x=0:0.1:1.07
y=linspace(0,1.07,11)
v(i)
v(i1:h:i2)
v(i1:i2)
v([i,j,k])
v(end)
v=[-1 3 2 4 -8 7]
v(2)
v(end)
v(2)+5
v(2)=6
v(2:4)
w=v(2:4)
u=v([1, 5, 6])
A = [1 2 3; -1 4 8; 7 2 1];
A
A = [1 2 3; -1 4 8]
B = [5 5 5; 6 6 6; 7 7 7]
C = [A; B]
A = ones(5)
B = ones(3,4)
C = zeros(5)
D = zeros(3,4)
E = eye(4)
F = eye(3,4), G = eye(4,3)

A(i,j) % Devuelve el elemento (i,j) de la matriz A.
A(i1:h:i2,j1:k:j2) % Devuelve la submatriz de A formada por las filas de la i1 a la i2 con incremento b y las columnas j1 a la j2 con incremento k.

A(i1:i2,j1:j2) % Devuelve la submatriz de A formada por las filas de la i1 a la i2 y las columnas j1 a la j2.
A(i1:h:i2,:) % Devuelve la submatriz de A formada por las filas de la i1 a la i2 con incremento h.
A(i1:i2,j) % Devuelve el elemento j de las filas comprendidas entre la i1 y la i2.

A(i,j1:j2) % Devuelve el elemento i de las columnas comprendidas entre la j1 y la j2.
A(:,j) % Devuelve el elemento j de todas las filas, o sea, la columna j.
A(i,:) % Devuelve el elemento i de todas las columnas, o sea, la fila i.
A(i,[j k]) % Devuelve la submatriz (aij, aik)

A = [1 2 3 4 5; 6 7 8 9 10; 11 12 13 14 15;
16 1 18 19 20]
A(2,5)
A(1:3,2:5) %filas 1 a 3, columnas 2 a 5.
A(1:2:4,1:3:5)
%filas 1, 3, columnas 1, 4 A([1 3], [1 4])
A(:,1:2:5) % todas las filas, columnas 1, 3 y 5.

A(2:4,3) % filas 2 a 4, columna 3
A(2,1:4) %fila 2, columnas 1 a 4
A(:,3)
B=[A(1:3,:) A(2:4,:)]
C=[A(1:3, 1:3); A(:,[1 3 5])]
D = A([2 4], [3 5])


y = 28
a = 20/3
ans = 2
ans = 2453/6780
ans = -5
ans = 5
ans = -6
ans = 5
ans = -5
ans = 6
ans = -6
ans = 6
ans =

          1          3          5         -7     33/100    355/113  2721/1001

ans =

          1          3          5         -7     33/100    355/113  2721/1001

v =

          1          3          5         -7     33/100    355/113  2721/1001

ans =

         10         12         14         16         18         20

ans =

         15         16         17         18         19

ans =

          1        3/2          2

ans =

         20     197/10       97/5     191/10       94/5       37/2       91/5

ans =

         11         12         13         14         15

ans =

         -3         -2         -1          0          1          2          3

ans =

         17         18         19         20

x =

 Columns 1 through 7:

         -3         -2         -1          0          1          2          3

 Columns 8 through 12:

          4          5          6  