# Introducción a Matlab (Octave) #

## ¿Qué es Matlab? ##

- Es un entorno matemático multiparadigma.
- Es un lenguaje de programación.
- Escrito en C, C++ y Java.
- Se creó en **1984**.
- Es un software privativo, patentado por *Mathworks*.
- Cleve Barry Moler es el padre del programa.
- [Sitio web oficial de Matlab]()

<p align="center">
  <img src="https://upload.wikimedia.org/wikipedia/commons/2/21/Matlab_Logo.png" width="250">
</p>

## ¿Qué es GNU Octave? ##

- Fue creado en **1988**.
- Es un software libre (con licencia GPL).
- Escrito en C, C++, Fortran.
- Se le reconoce como padre a John W. Eaton.
- Se llama en honor al ingeniero químico *Octave Levenspiel*.
- [Sitio web oficial de GNU Octave](https://www.gnu.org/software/octave)
- Si no desea instalar Octave en su ordenador, puede probar la versión cloud [aquí](https://www.verbosus.com)

<p align="center">
  <img src="https://www.gnu.org/software/octave/img/octave-logo.svg"  width="250">
</p>

### Aspectos en común ###

- Se usan en la enseñanza de **álgebra lineal**, **análisis numérico**, entre otros.
- Ambos programas ejecutan ficheros con extensión `.m` (Sí y solo sí la sintáxis es común en ambos, esto se comentará a lo largo de los apuntes).

### Diferencias ###

- Octave admite operadores de autoincrementación y asignación de estilo C. (Si está llevando el curso CC101 *Introducción a la Ciencia de la Computación* o CC102 *Introducción a la Programación*).
- MATLAB no permite espacios en blanco antes del operador de trasposición, pero Octave sí (es solo un operador como otros).
- MATLAB siempre requiere ... para la continuación de línea.
- Más diferencias se mostrará en los próximos apuntes :smile:

### Otros competidores de Matlab ###

Sus competidores naturales son los programas [Maple](https://www.maplesoft.com/products/Maple), [Mathematica](https://www.wolfram.com/mathematica), [SageMath](https://www.sagemath.org), [Scilab](https://www.scilab.org), [Freemat](http://freemat.sourceforge.net/), [Julia](https://julialang.org/), [R](https://www.r-project.org), [Perl](http://pdl.perl.org), así como las librerías [Numpy](http://www.numpy.org), [SciPy](https://www.scipy.org), [matplotlib](https://matplotlib.org) para Python, [SciLua](http://scilua.org) y [torch](http://torch.ch) para Lua, [SciRuby](http://sciruby.com) para Ruby y [Numeric.js](http://www.numericjs.com) para Javascript.

## Compatibilidad de GNU Octave con Matlab ##

1. Matrices como tipo de datos fundamentales.
2. Soporte integrado para números complejos.
3. Potentes funciones integradas de matemáticas y extensas bibliotecas de funciones.
4. Extensibilidad en forma de funciones definidas por el usuario.

En Matlab el `;` (semicolon) al final del comando indica que la acción se ejecutará, mas no se imprimirá. Sin embargo en GNU Octave se mostrará la salida.

In [9]:
# hola mundo. Comentario del tipo I. (Works with GNU Octave)
% hola mundo. Comentario del tipo II. (Works both Matlab or GNU Octave)
%{
Este es un comentario
multilínea, análogo al /*foo*/
en C.
%}
disp('Hola mundo');

Hola mundo


Para ver la versión, escribiremos desde el **Command Window**, en el caso de Matlab también mostrará los *Toolbox's*

In [10]:
ver

----------------------------------------------------------------------
GNU Octave Version: 4.2.1
GNU Octave License: GNU General Public License
Operating System: Linux 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64
----------------------------------------------------------------------
no packages installed.


Escriba version y verá en el *Workspace* que se guarda en la variable ans de clase *char*.

In [11]:
version

ans = 4.2.1


Para limpiar el **Window Command** en tanto en Matlab como Octave digite `clc`, pero también puede usar la combinación de teclas `Ctrl+l` (solo en GNU Octave).

Los objetos con los que trabajaremos serán **_matrices_**, un número real o complejo (escalar) es una matriz de orden 1, un vector columna y un vector fila también son matrices.

$$\mathbf{A}= 
 \begin{bmatrix}
 a_{11} & a_{12} & \cdots & a_{1n} \\
 a_{21} & a_{22} & \cdots & a_{2n} \\
 \vdots & \vdots & \ddots & \vdots \\
 a_{m1} & a_{m2} & \cdots & a_{mn}
 \end{bmatrix}= 
\left( \begin{array}{rrrr}
 a_{11} & a_{12} & \cdots & a_{1n} \\
 a_{21} & a_{22} & \cdots & a_{2n} \\
 \vdots & \vdots & \ddots & \vdots \\
 a_{m1} & a_{m2} & \cdots & a_{mn}
 \end{array}\right)=\left(a_{ij}\right)\in\mathbb{K}^{m\times n}.$$

Definimos la matriz $\mathbf{A}= 
 \begin{bmatrix}
 1 & 2 & 3 & 4 & 5\\
 6 & 7 & 8 & 9 & 10\\
 11 & 12 & 13 & 14 & 15\\
 16 & 17 & 18 & 19 & 20
 \end{bmatrix}$ con el siguiente comando:

Para cambiar el formato de los números usaremos el comando `format`. Veamos la siguiente tabla:

| Formato de salida | Definición |
| :---:     		| :---:	     |
|short	            |cuatro cifras decimales|
|long               | 15 decimales          |
| hex               | cifras hexadecimales|
| bank  | dos cifras decimales|
| shor e | notación científica con cuatro decimales|
| long e| notación científica con 15 decimales|
| rational | expresa como fracciones|

In [12]:
format long # Formato con 15 decimales.
pi
format # Regresa al formato short de 4 decimales.
pi
format rat # Formato como fracción.
pi

ans =  3.14159265358979
ans =  3.1416
ans = 355/113


In [13]:
A = [1:5;6:10;11:15;16:20] # Matriz A de orden 4 x 5.

A =

          1          2          3          4          5
          6          7          8          9         10
         11         12         13         14         15
         16         17         18         19         20



## Matriz traspuesta ##
Se llama *matriz traspuesta* de una matriz cualquiera $\mathbf{A}$ y la representamos por $\mathbf{A}^{\prime}$, a aquella obtenido de la $\mathbf{A}$, cambiando ordenadamente sus filas por sus columnas; es decir, si $\mathbf{A}=(a_{ij}), \mathbf{A}^{\prime}={({a}_{ij})}^{\prime}=({a}_{ij})$.
Para hallar la matriz traspuesta del ejemplo, simplemente escribimos:

In [14]:
A'

ans =

          1          6         11         16
          2          7         12         17
          3          8         13         18
          4          9         14         19
          5         10         15         20



## Propiedades de la matriz transpuesta ##
1. La traspuesta de la transpuesta de una matriz $\mathbf{A}=({a}_{ij})$ es ella misma.
2. La traspuesta de una suma de matrices es la suma de las traspuestas de dichas matrices.
3. La traspuesta del producto de matrices es el producto de las traspuestas, permutando los factores; es decir:
$${(A_{m\times n}\cdot B_{n\times p})}^{\prime}={B}^{\prime}_{p\times n}\cdot{A}^{\prime}_{n\times m}$$

## Matriz simétrica ##

Se denomina *matriz simétrica* a aquella matriz $\mathbf{A}$ tal que ${\mathbf{A}}^{\prime}=\mathbf{A}$, o lo que es lo mismo, a aquella matriz tal que ${a}_{ij}={a}_{ji}\,\forall i,j$.

Claro está que una condición necesaria es que la matriz sea **cuadrada**.

## Matriz antisimétrica ##

Se dice que la matriz $A$ es una *matriz antisimétrica* si ${\mathbf{A}}^{\prime}=-\mathbf{A}$, es decir, si ${a}_{ij}={-a}_{ji}\,\forall i,j$.

Necesariamente, los elementos $a_{ii}$ de la diagonal principal de una matriz antisimétrica deberán ser nulos, ya que como $a_{ii}={-a}_{ii}$, se tendrá que $2{a}_{ii}=0 \implies a_{ii}=0$.

### Propiedades ###
1. Si $\mathbf{A}$ es una matriz simétrica y $\alpha\in\mathbb{K}$, entonces $\alpha\cdot\mathbf{A}$ es simétrica.
2. Si $\mathbf{A}$ es una matriz cuadrada, entonces las matrices $\mathbf{A}+{\mathbf{A}}^{\prime}$ y $\mathbf{A}\cdot{\mathbf{A}}^{\prime}$ son simétricas, y la matriz $\mathbf{A}-{\mathbf{A}}^{\prime}$ es antisimétrica.
3. Cualquier matriz cuadrada $\mathbf{A}$ puede descomponerse de forma única, en suma de una matriz simétrica más otra matriz antisimétrica.

## Operaciones de rutina ##
Para asignar una definir una variable, digite:

In [15]:
a = 15 + 0.25-16/3.6
B = [1 2 ; 3 4] % Nótese que los 'semicolon' indican el final de la fila.
C = [3+2i -5 -i ; 4-3.1i 14 0] % También podemos ingresar valores complejos.

a = 389/36
B =

          1          2
          3          4

C =

          3 +         2i         -5 +         0i         -0 -         1i
          4 -     31/10i         14 +         0i          0 +         0i



## El comando who y whos ##
En Command Window escriba `who` para listar las variables utilizadas durante su sesión de estudio, si desea conocer más detalles, como por ejemplo, el espacio de memoria ocupada, el tipo de dato
Para 'eliminar una variable' digite `clear nombre_de_la_variable` y verá que desaparece de la lista en el Workspace, pero si desea eliminar todas las variables digite `clear` o `clear all`.

In [16]:
A = magic(5) # Matriz mágica de orden 5.
eps # Número positivo tal que al ser sumado 1, eps supera a 1.
who # Nos lista las variables en el alcance actual.
whos # Nos lista las variables, pero con detalles como el tamaño de la matriz, bytes y clase; y el total en espacio.

A =

         17         24          1          8         15
         23          5          7         14         16
          4          6         13         20         22
         10         12         19         21          3
         11         18         25          2          9

ans = 0
Variables in the current scope:

A    B    C    a    ans  n

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        A           5x5                        200  double
        B           2x2                         32  double
   c    C           2x3                         96  double
        a           1x1                          8  double
        ans         1x1                          8  double
        n           1x1                          8  double

Total is 38 elements using 352 bytes



## Funciones elementales ##
Las funciones definidas por el usuario la podemos ver con el comando

**Ejercicio 1:**
Calcule:

$$\displaystyle I=\int_{1}^{e}\frac{\mathrm{d}x}{x}$$

**Solución**
Por el Primer teorema fundamental del cálculo, una antiderivada es log x. Y del segundo teorema fundamental del cálculo resulta:

In [17]:
# Ejercicio 1. Una antiderivada de f(x)=1/x es log(x).
I = log(exp(1)) - log(exp(0))

I = 1


### Ingreso de datos ###

Otra manera de asignar es con el comando `input`, veamos un ejemplo:

In [18]:
n = input (' Ingrese un valor: ' ); # Como el scanf en C :)

 Ingrese un valor:20


### Extra ###
En algunas universidades de Brasil usan Matlab para su curso de Matemática Básica 2 (cuyo estudio son las matrices y transformaciones lineales) y en algunas universidades de Ginebra se enseña Matlab desde el primer ciclo.

[¡Vamos a la segunda clase!](https://github.com/carlosal1015/MATLAB/blob/master/Clase%201/Primera%20clase.ipynb)